### PR TITLE
fix for android tv and stremio web

### PR DESCRIPTION
**Pull request by dexter21767**
having catalogElement.behaviorHints.defaultVideoId equal to catalogElement.id is the only way to get streams to show properly on android tv and stremio web

### CODE REVIEW

**Comment by anime-src** [comment]
Thanks @dexter21767

**Comment by dexter21767-dev** [comment]
@anime-src dont forget to deploy the update

**Comment by anime-src** [comment]
Sorry, Im not deploying, never did, it's up to who needs it to deploy it, private hosting or public to share

**Comment by anime-src** [comment]
@dexter21767-dev  deployed on https://86f0740f37f6-hanime-stremio.baby-beamup.club/manifest.json

**Pull request merged**
